name: ofa-gpu

channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.7
  - ccache
  - cmake
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - cxx-compiler
  - jupyterlab
  - mpi4py # installs cuda-aware openmpi
  - nccl
  - nvcc_linux-64=11.2
  - openmpi
  - pip
  - matplotlib
  - opencv
  - pip:
    - numpy
    - torch==1.8.1
    - torchaudio==0.8.1
    - torchvision==0.9.1
    - torchsummary
    - filelock
    - PyYaml
    - tqdm
    - thop
    - horovod
    - -e .